package clasesPropias;

//CONVERTIMOS UNA CLASE NORMAL EN UNA CLASE GENERICA 
//T=PARÁMETRO ARGUMENTO DE TIPO, SE USAN MAYÚSCULAS Y SE USAN LAS LETRAS T-U-K.

public class A0_165_Pareja <T> {
	
	//ESTE CONSTRUCTO, SOLO LE DÁ UN ESTADO INICIAL AL CAMPO DE CLASE "PRIMERO" QUE ES IGUAL NULL.
	public A0_165_Pareja() {
		primero=null;
	}
	
	
	
	//CREAMOS UN SETTER QUE SEA CAPAS DE CAMBIAR EL VALOR DEL CAMPO DE CLASE "PRIMERO".
	//ESTE MÉTODO HACE QUE EL CAMPO DE CLASE "PRIMERO" DEBE SER IGUAL AL ARHUMENTO QUE LE PASAMOS POR.. 
	//..PARÁMETRO.
	public void setPrimero(T nuevoValor) {
		primero = nuevoValor;
		
	}
	
	
	//MÉTODO GETTER, SE ENCARGA DE DEVOLVERNOS EL OBJETOS QUE ESTEMOS MANEJANDO EN CADA OCASIÓN.
	//PONEMOS QUE NOS VA A DEVOLVER UN OBJ DE TIPO GENERICO "T" y QUE TODAVÍA NO SABEMOS CUAL ES.
	public T getPrimero() {
		return primero;
	}
	
	
	//CAMPO DE CLASE
	private T primero;
}
